"use client";

import { useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import PlayerCard from "./PlayerCard";
import SelectedTeam from "./SelectedTeam";
import type { Player, Pool } from "@/lib/types";
import { createClient } from "@/lib/supabase/client";

interface ExistingEntry {
  id: string;
  display_name: string;
  token: string;
}

interface ExistingPick {
  player_id: string;
  pick_slot: number;
}

interface PlayerPickerProps {
  players: Player[];
  poolId: string;
  pool: Pool;
  existingEntry: ExistingEntry | null;
  existingPicks: ExistingPick[];
  existingToken: string | null;
}

export default function PlayerPicker({
  players,
  poolId,
  pool,
  existingEntry,
  existingPicks,
  existingToken,
}: PlayerPickerProps) {
  const router = useRouter();
  const maxPicks = pool.max_picks;

  const [search, setSearch] = useState("");
  const [selectedIds, setSelectedIds] = useState<string[]>(
    existingPicks
      .sort((a, b) => a.pick_slot - b.pick_slot)
      .map((p) => p.player_id)
  );
  const [displayName, setDisplayName] = useState(existingEntry?.display_name ?? "");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return players.filter(
      (p) =>
        p.full_name.toLowerCase().includes(q) ||
        p.country.toLowerCase().includes(q)
    );
  }, [players, search]);

  function togglePlayer(playerId: string) {
    setSelectedIds((prev) => {
      if (prev.includes(playerId)) return prev.filter((id) => id !== playerId);
      if (prev.length >= maxPicks) return prev;
      return [...prev, playerId];
    });
  }

  function removePlayer(playerId: string) {
    setSelectedIds((prev) => prev.filter((id) => id !== playerId));
  }

  async function handleSave() {
    if (selectedIds.length !== maxPicks) {
      setError(`Please select exactly ${maxPicks} players.`);
      return;
    }
    if (!displayName.trim()) {
      setError("Please enter your name.");
      return;
    }

    setSaving(true);
    setError("");

    const supabase = createClient();

    try {
      let entryId = existingEntry?.id;
      let token = existingToken;

      if (entryId && token) {
        // Update existing entry
        await supabase
          .from("entries")
          .update({ display_name: displayName.trim(), updated_at: new Date().toISOString() })
          .eq("id", entryId)
          .eq("token", token);

        await supabase.from("entry_picks").delete().eq("entry_id", entryId);
      } else {
        // Create new entry — token is generated by DB default
        const { data: newEntry, error: entryError } = await supabase
          .from("entries")
          .insert({
            pool_id: poolId,
            display_name: displayName.trim(),
          })
          .select("id, token")
          .single();

        if (entryError || !newEntry) throw entryError ?? new Error("Failed to create entry");
        entryId = newEntry.id;
        token = newEntry.token;

        // Save token in a cookie so this browser can edit picks later
        document.cookie = `entry_token_${poolId}=${token}; path=/; max-age=${60 * 60 * 24 * 365}; SameSite=Lax`;
      }

      // Insert picks
      const picks = selectedIds.map((player_id, i) => ({
        entry_id: entryId!,
        player_id,
        pick_slot: i + 1,
      }));

      const { error: picksError } = await supabase
        .from("entry_picks")
        .insert(picks);

      if (picksError) throw picksError;

      router.push(`/pool/${poolId}/entry/${entryId}`);
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong. Try again.");
      setSaving(false);
    }
  }

  const selectedPlayers = selectedIds
    .map((id) => players.find((p) => p.id === id))
    .filter(Boolean) as Player[];

  return (
    <div className="flex flex-col lg:flex-row gap-6">
      {/* Left: player list */}
      <div className="flex-1 min-w-0">
        <div className="mb-4">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">
            {existingEntry ? "Edit Your Team" : "Make Your Picks"}
          </h1>
          <p className="text-gray-500 text-sm">
            Select {maxPicks} players. Each round, your best {pool.scoring_keep} scores count.
          </p>
        </div>

        {/* Name input */}
        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Your name (shown on leaderboard)
          </label>
          <input
            type="text"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
            placeholder="e.g. John Smith"
            maxLength={40}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-masters-green text-sm"
          />
        </div>

        {/* Search */}
        <div className="mb-4">
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search players..."
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-masters-green text-sm"
          />
        </div>

        {/* Player grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {filtered.map((player) => (
            <PlayerCard
              key={player.id}
              player={player}
              isSelected={selectedIds.includes(player.id)}
              isFull={selectedIds.length >= maxPicks && !selectedIds.includes(player.id)}
              onToggle={() => togglePlayer(player.id)}
            />
          ))}
        </div>

        {filtered.length === 0 && (
          <div className="text-center py-8 text-gray-400">
            No players found for &quot;{search}&quot;
          </div>
        )}
      </div>

      {/* Right: selected team sticky panel */}
      <div className="lg:w-72 lg:flex-shrink-0">
        <div className="lg:sticky lg:top-6">
          <SelectedTeam
            players={selectedPlayers}
            maxPicks={maxPicks}
            onRemove={removePlayer}
            onSave={handleSave}
            saving={saving}
            error={error}
            displayName={displayName}
          />
        </div>
      </div>
    </div>
  );
}
