-- 2025 Masters Field (approx 89 players)
-- World rankings as of early April 2025 (approximate)

insert into players (full_name, country, world_ranking) values
  -- Top ranked
  ('Scottie Scheffler', 'USA', 1),
  ('Rory McIlroy', 'NIR', 2),
  ('Xander Schauffele', 'USA', 3),
  ('Jon Rahm', 'ESP', 4),
  ('Collin Morikawa', 'USA', 5),
  ('Viktor Hovland', 'NOR', 6),
  ('Patrick Cantlay', 'USA', 7),
  ('Wyndham Clark', 'USA', 8),
  ('Tommy Fleetwood', 'ENG', 9),
  ('Shane Lowry', 'IRL', 10),
  ('Tyrrell Hatton', 'ENG', 11),
  ('Ludvig Aberg', 'SWE', 12),
  ('Max Homa', 'USA', 13),
  ('Tony Finau', 'USA', 14),
  ('Cameron Young', 'USA', 15),
  ('Russell Henley', 'USA', 16),
  ('Min Woo Lee', 'AUS', 17),
  ('Tom Kim', 'KOR', 18),
  ('Sungjae Im', 'KOR', 19),
  ('Corey Conners', 'CAN', 20),
  ('Sahith Theegala', 'USA', 21),
  ('Sepp Straka', 'AUT', 22),
  ('Chris Kirk', 'USA', 23),
  ('Brian Harman', 'USA', 24),
  ('Justin Rose', 'ENG', 25),
  ('Matt Fitzpatrick', 'ENG', 26),
  ('Robert MacIntyre', 'SCO', 27),
  ('Si Woo Kim', 'KOR', 28),
  ('Keegan Bradley', 'USA', 29),
  ('Billy Horschel', 'USA', 30),
  ('Akshay Bhatia', 'USA', 31),
  ('Nick Dunlap', 'USA', 32),
  ('Harris English', 'USA', 33),
  ('Jake Knapp', 'USA', 34),
  ('Joaquin Niemann', 'CHI', 35),
  ('Cameron Smith', 'AUS', 36),
  ('Christiaan Bezuidenhout', 'RSA', 37),
  ('Thriston Lawrence', 'RSA', 38),
  ('Adrian Meronk', 'POL', 39),
  ('Alex Noren', 'SWE', 40),
  ('Patrick Reed', 'USA', 41),
  ('Bryson DeChambeau', 'USA', 42),
  ('Brooks Koepka', 'USA', 43),
  ('Jordan Spieth', 'USA', 44),
  ('Dustin Johnson', 'USA', 45),
  ('Hideki Matsuyama', 'JPN', 46),
  ('Will Zalatoris', 'USA', 47),
  ('Lucas Glover', 'USA', 48),
  ('Jason Day', 'AUS', 49),
  ('Adam Scott', 'AUS', 50),
  ('Kurt Kitayama', 'USA', 51),
  ('Rickie Fowler', 'USA', 52),
  ('Davis Riley', 'USA', 53),
  ('Brendan Steele', 'USA', 54),
  ('Denny McCarthy', 'USA', 55),
  ('Ryan Fox', 'NZL', 56),
  ('Andrew Putnam', 'USA', 57),
  ('Eric Cole', 'USA', 58),
  ('Victor Perez', 'FRA', 59),
  ('Matthieu Pavon', 'FRA', 60),
  ('Mark Hubbard', 'USA', 61),
  ('Aaron Rai', 'ENG', 62),
  ('Callum Shinkwin', 'ENG', 63),
  ('Taylor Moore', 'USA', 64),
  ('Austin Eckroat', 'USA', 65),
  ('Davis Thompson', 'USA', 66),
  ('Harry Hall', 'ENG', 67),
  ('Nico Echavarria', 'COL', 68),
  ('Sam Burns', 'USA', 69),
  ('J.T. Poston', 'USA', 70),
  -- Past champions (automatic invites)
  ('Tiger Woods', 'USA', 200),
  ('Phil Mickelson', 'USA', 180),
  ('Sergio Garcia', 'ESP', 90),
  ('Bubba Watson', 'USA', 160),
  ('Zach Johnson', 'USA', 175),
  ('Trevor Immelman', 'RSA', 999),
  ('Mike Weir', 'CAN', 999),
  ('Jose Maria Olazabal', 'ESP', 999),
  ('Fred Couples', 'USA', 999),
  ('Bernhard Langer', 'GER', 999),
  ('Larry Mize', 'USA', 999),
  ('Charles Coody', 'USA', 999),
  ('Sandy Lyle', 'SCO', 999),
  -- Additional qualifiers
  ('Tom Hoge', 'USA', 75),
  ('Kevin Yu', 'TPE', 76),
  ('Stephan Jaeger', 'GER', 77),
  ('Taylor Pendrith', 'CAN', 78),
  ('Ben Griffin', 'USA', 79),
  ('Michael Kim', 'USA', 80),
  ('Amateur qualifier 1', 'USA', 9999),
  ('Amateur qualifier 2', 'USA', 9999)
on conflict do nothing;
