-- Remove auth requirement from entries
ALTER TABLE entries ADD COLUMN IF NOT EXISTS token uuid DEFAULT gen_random_uuid();
ALTER TABLE entries ALTER COLUMN user_id DROP NOT NULL;

-- Drop old auth-based entry policies
DROP POLICY IF EXISTS "entries_insert_own" ON entries;
DROP POLICY IF EXISTS "entries_update_own" ON entries;
DROP POLICY IF EXISTS "entry_picks_write_own" ON entry_picks;

-- Anyone can insert an entry (token is generated by DB, returned to client)
CREATE POLICY "entries_insert_anon" ON entries
  FOR INSERT WITH CHECK (true);

-- Anyone can update entries (token match enforced in app code via .eq("token", token))
CREATE POLICY "entries_update_anon" ON entries
  FOR UPDATE USING (true);

-- Anyone can insert picks for an existing entry
CREATE POLICY "entry_picks_insert_anon" ON entry_picks
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM entries WHERE id = entry_id)
  );

-- Anyone can delete picks (deadline + token enforced in app code)
CREATE POLICY "entry_picks_delete_anon" ON entry_picks
  FOR DELETE USING (true);
